In [1]:
import pandas as pd
dataframe = pd.read_csv('Absenteeism_at_work.csv')
dataframe.head()

ID  Reason for absence  Month of absence  Day of the week  Seasons  \
0  11                  26                 7                3        1   
1  36                   0                 7                3        1   
2   3                  23                 7                4        1   
3   7                   7                 7                5        1   
4  11                  23                 7                5        1   

   Transportation expense  Distance from Residence to Work  Service time  Age  \
0                     289                               36            13   33   
1                     118                               13            18   50   
2                     179                               51            18   38   
3                     279                                5            14   39   
4                     289                               36            13   33   

   Work load Average/day   Hit target  Disciplinary failure  Education  \
0                 239.554          97                     0          1   
1                 239.554          97                     1          1   
2                 239.554          97                     0          1   
3                 239.554          97                     0          1   
4                 239.554          97                     0          1   

   Body mass index  Absenteeism time in hours  
0               30                          4  
1               31                          0  
2               31                          2  
3               24                          4  
4               30                          2

In [2]:
# Example of Splitting a Contrived Dataset into Train and Test
from random import seed
from random import randrange

# Split a dataset into a train and test set
def train_test_split(dataset, split=0.60):
    train = list()
    train_size = split * len(dataset)
    dataset_copy = list(dataset)
    while len(train) < train_size:
        index = randrange(len(dataset_copy))
        train.append(dataset_copy.pop(index))
    return train, dataset_copy

# test train/test split
seed(1)
dataset = 'Absenteeism_at_work.csv'
train, test = train_test_split(dataset)
print(train)
print(test)

['n', '.', 's', 'm', 't', 'c', 'k', 'v', '_', 's', 's', 'e', 'b', 'w']
['A', 'e', 'e', 'i', '_', 'a', 't', 'o', 'r']


In [7]:
# Split-out validation dataset
array = dataframe.values
X = array[:,0:15]
Y = array[:,14]
#validation_size = 0.20
seed = 7
X_train, X_validation, Y_train, Y_validation = train_test_split(X, Y, test_size=.2, random_state=seed)

TypeError: train_test_split() got an unexpected keyword argument 'test_size'

In [9]:
import numpy as np
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, Y, test_size=0.33, random_state=42)

In [10]:
X_train

array([[11., 19.,  7., ...,  1., 30.,  8.],
       [34., 10.,  6., ...,  1., 28.,  3.],
       [ 5.,  0., 10., ...,  1., 38.,  0.],
       ...,
       [ 3., 11.,  9., ...,  1., 31.,  8.],
       [28., 25.,  5., ...,  1., 24.,  3.],
       [28., 23., 12., ...,  1., 24.,  2.]])

In [11]:
X_test

array([[28., 27.,  1., ...,  1., 24.,  1.],
       [33., 26.,  4., ...,  1., 32.,  4.],
       [20., 10., 11., ...,  1., 23.,  8.],
       ...,
       [34., 19., 12., ...,  1., 28., 56.],
       [34., 19.,  1., ...,  1., 28.,  1.],
       [34., 10.,  4., ...,  1., 28.,  2.]])

In [12]:
y_train

array([  8.,   3.,   0.,   3.,   4.,   8.,   2.,   2.,   8.,   2.,   3.,
         2.,   8.,   8.,   8.,   4.,   8.,   8.,  80.,  16.,   8.,   4.,
         8.,   8.,   2.,   2.,   3.,   8.,   4.,   1.,   8.,   4.,   2.,
         2.,   2.,   1.,   4.,   8.,  32.,  40.,   8.,   2.,   3.,   2.,
         2.,   0.,   2.,   4.,   3.,   1.,   3.,   1.,   1.,   3.,   0.,
         1.,   8.,   4.,   0.,   3.,   0.,   1.,   3.,  16.,   1.,   3.,
         2.,   2.,   2.,   8.,   8.,   4.,   2.,   1.,   2.,   8.,   8.,
         8.,   8.,   8.,   3.,   3.,  16.,   2.,   3.,   8.,   4.,   1.,
         3.,   4.,   8.,   1.,   4.,   8.,   3.,   8.,   1.,   0.,   2.,
         3.,   1.,   3.,   8.,   2.,   0.,   8.,   8.,   3.,   3.,   2.,
         8.,   8.,  24.,   8.,   2.,   8.,   3.,   1.,   8.,   8.,   1.,
       120.,  16.,   1.,   4.,   8.,   2.,   3.,   8.,   3.,   3.,   2.,
         8.,   2.,   0.,   1.,   8.,   2.,   8.,   7.,   0.,   8.,   8.,
         8.,   3.,   1.,   1.,  24.,   8.,   8.,   

In [13]:
 y_test

array([  1.,   4.,   8.,   2.,   4.,   2.,   2.,   5.,   8.,   1.,   0.,
         0.,   4.,   8.,   0.,  24.,   1.,   3.,   8.,   4.,   3.,   1.,
         8.,   0.,   2.,   3.,   1.,   2.,   2.,   8.,   8.,   3.,   8.,
         3.,   1.,   3.,   8.,   2.,   8.,   8.,   3.,   8.,   2.,   2.,
         2.,   2.,   8.,   8.,   3.,   1.,   2.,  16.,   8.,   3.,   1.,
         0.,   2.,   0.,   8.,   8.,   8.,   2.,  24.,   8.,   8.,   8.,
         3.,   3.,   4.,  24.,   2.,   8.,   8.,   2.,   1.,   8.,   3.,
         3.,   8.,  32.,   1.,   2.,   8.,   8.,   8.,   0.,   4.,  40.,
         8.,   8.,   2.,   0.,   4.,   1.,   8.,   2.,   2.,   8.,   3.,
         8.,   2.,  80.,   8.,   2.,   8.,   3.,   8.,   2.,   0.,   1.,
         8.,   2.,   5.,   3.,  80.,   8.,   2.,   2.,   8.,  16.,   4.,
         1.,   8.,   4.,   1.,   1.,   0.,   2.,   8.,   1.,   3.,   1.,
         2.,   3.,   4.,   8.,  16.,   2.,   1.,   4.,   3.,   4.,  24.,
         2.,   1.,   2.,   2.,   2.,   8.,   0.,   

In [14]:
# Evaluate using Cross Validation
from pandas import read_csv
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression
#filename = 'pima-indians-diabetes.data.csv'
#names = ['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi', 'age', 'class']
#dataframe = read_csv(filename, names=names)
array = dataframe.values
X = array[:,0:15]
Y = array[:,14]
kfold = KFold(n_splits=10, random_state=7)
model = LogisticRegression()
results = cross_val_score(model, X, Y, cv=kfold)
print("Accuracy: %.3f%% (%.3f%%)" % (results.mean()*100.0, results.std()*100.0))

/home/felipemartinezs/.local/lib/python3.5/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/felipemartinezs/.local/lib/python3.5/site-packages/sklearn/linear_model/logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)
/home/felipemartinezs/.local/lib/python3.5/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/felipemartinezs/.local/lib/python3.5/site-packages/sklearn/linear_model/logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)
/home/felipemartinezs/.local/lib/python3.5/site-pa

Accuracy: 61.081% (7.297%)


/home/felipemartinezs/.local/lib/python3.5/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/felipemartinezs/.local/lib/python3.5/site-packages/sklearn/linear_model/logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)
/home/felipemartinezs/.local/lib/python3.5/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/felipemartinezs/.local/lib/python3.5/site-packages/sklearn/linear_model/logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)
